"""Runtime tests for our NetworkPolicies using the pure-Python simulator.

Three test classes:

  * `TestSelectors`         — selector matching primitives (matchLabels,
                              matchExpressions In/NotIn/Exists, namespaceSelector,
                              the Day 8 canonical-label regression)
  * `TestPolicyEvaluation`  — core decision algorithm (default-allow,
                              default-deny once selected, multi-policy union,
                              port/protocol, ipBlock + except)
  * `TestGeneratedPolicies` — loads the actual `network-policies-per-agent.yaml`
                              generated by `scripts/security/generate_policies.py`
                              and asserts each agent reaches what capabilities.yaml
                              says it should reach (and nothing else)
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
import yaml

from tests.security.policy_simulator import (
    Cluster,
    Decision,
    Namespace,
    Pod,
    _ip_matches_block,
    _matches_selector,
    _port_matches,
)

pytestmark = [pytest.mark.unit]


# ============================================================
# 1. Low-level selector + helper tests
# ============================================================

class TestSelectors:
    def test_empty_selector_matches_anything(self):
        assert _matches_selector({"app": "redis"}, {})
        assert _matches_selector({}, {})

    def test_match_labels_exact(self):
        assert _matches_selector({"app": "redis"}, {"matchLabels": {"app": "redis"}})

    def test_match_labels_extra_labels_on_pod_ok(self):
        """K8s spec: pod labels are a superset of selector labels."""
        assert _matches_selector(
            {"app": "redis", "tier": "data"},
            {"matchLabels": {"app": "redis"}},
        )

    def test_match_labels_missing_required_label_rejects(self):
        assert not _matches_selector({"tier": "data"}, {"matchLabels": {"app": "redis"}})

    def test_match_labels_wrong_value_rejects(self):
        assert not _matches_selector(
            {"app": "postgres"}, {"matchLabels": {"app": "redis"}}
        )

    def test_match_expressions_in_operator(self):
        sel = {"matchExpressions": [{"key": "tier", "operator": "In", "values": ["data", "cache"]}]}
        assert _matches_selector({"tier": "data"}, sel)
        assert _matches_selector({"tier": "cache"}, sel)
        assert not _matches_selector({"tier": "web"}, sel)

    def test_match_expressions_notin_operator(self):
        sel = {"matchExpressions": [{"key": "env", "operator": "NotIn", "values": ["prod"]}]}
        assert _matches_selector({"env": "dev"}, sel)
        assert not _matches_selector({"env": "prod"}, sel)

    def test_match_expressions_exists_operator(self):
        sel = {"matchExpressions": [{"key": "feature.x", "operator": "Exists"}]}
        assert _matches_selector({"feature.x": "anything"}, sel)
        assert not _matches_selector({"other": "x"}, sel)

    def test_namespace_canonical_constructor_sets_metadata_name_REGRESSION(self):
        """Day 8 regression — our namespace-selector for kube-system uses
        the apiserver-auto-applied label. The Namespace constructor we
        use in tests must mirror that, or every other test silently
        misses the bug."""
        ns = Namespace.canonical("kube-system")
        assert ns.labels == {"kubernetes.io/metadata.name": "kube-system"}

    def test_namespace_selector_with_canonical_label_matches_REGRESSION(self):
        """Our generated DNS rule uses {kubernetes.io/metadata.name: kube-system}.
        If a future edit reverts to the legacy {name: kube-system}, this
        test fires immediately."""
        ns = Namespace.canonical("kube-system")
        sel = {"matchLabels": {"kubernetes.io/metadata.name": "kube-system"}}
        assert _matches_selector(ns.labels, sel)

    def test_namespace_selector_with_legacy_name_label_misses(self):
        """A canonically-labeled namespace does NOT have a `name` label.
        This is the Day 8 bug demonstrated: silent miss."""
        ns = Namespace.canonical("kube-system")
        legacy_sel = {"matchLabels": {"name": "kube-system"}}
        assert not _matches_selector(ns.labels, legacy_sel)


# ============================================================
# 2. Port + IP block helpers
# ============================================================

class TestPortAndIP:
    def test_port_match_tcp_exact(self):
        assert _port_matches([{"port": 6379, "protocol": "TCP"}], 6379, "TCP")

    def test_port_match_protocol_default_is_tcp(self):
        """Protocol defaults to TCP when omitted in the policy spec."""
        assert _port_matches([{"port": 80}], 80, "TCP")
        assert not _port_matches([{"port": 80}], 80, "UDP")

    def test_port_mismatch_rejects(self):
        assert not _port_matches([{"port": 6379, "protocol": "TCP"}], 5432, "TCP")

    def test_port_udp_only_rejects_tcp(self):
        assert not _port_matches([{"port": 53, "protocol": "UDP"}], 53, "TCP")

    def test_port_dns_dual_tcp_udp(self):
        """Two entries in the ports list: rule matches if any entry matches."""
        dns_ports = [
            {"port": 53, "protocol": "UDP"},
            {"port": 53, "protocol": "TCP"},
        ]
        assert _port_matches(dns_ports, 53, "UDP")
        assert _port_matches(dns_ports, 53, "TCP")

    def test_ipblock_cidr_matches(self):
        assert _ip_matches_block("8.8.8.8", {"cidr": "0.0.0.0/0"})

    def test_ipblock_except_excludes_rfc1918(self):
        """Our anthropic rule: cidr 0.0.0.0/0 except [RFC 1918]."""
        block = {
            "cidr": "0.0.0.0/0",
            "except": ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"],
        }
        assert _ip_matches_block("1.1.1.1", block)          # public — allowed
        assert _ip_matches_block("104.16.0.1", block)       # anthropic-ish CDN range
        assert not _ip_matches_block("10.5.4.3", block)     # RFC1918 — excluded
        assert not _ip_matches_block("192.168.0.42", block)
        assert not _ip_matches_block("172.20.0.1", block)

    def test_ipblock_outside_cidr_rejects(self):
        assert not _ip_matches_block("8.8.8.8", {"cidr": "10.0.0.0/8"})


# ============================================================
# 3. Core decision algorithm
# ============================================================

NS_ORDINOX = "ordinox-ai"
NS_KUBE_SYSTEM = "kube-system"


def _basic_cluster() -> Cluster:
    """A small cluster used across most tests."""
    return Cluster(
        namespaces=[
            Namespace.canonical(NS_ORDINOX),
            Namespace.canonical(NS_KUBE_SYSTEM),
        ],
        pods=[
            Pod("echo-1",         NS_ORDINOX, {"app": "echo-agent"}),
            Pod("orch-1",         NS_ORDINOX, {"app": "orchestrator-agent"}),
            Pod("compliance-1",   NS_ORDINOX, {"app": "compliance-agent"}),
            Pod("analyst-1",      NS_ORDINOX, {"app": "analyst-agent"}),
            Pod("redis-0",        NS_ORDINOX, {"app": "redis"}),
            Pod("postgres-0",     NS_ORDINOX, {"app": "postgres"}),
            Pod("jaeger-1",       NS_ORDINOX, {"app": "jaeger"}),
            Pod("milvus-0",       NS_ORDINOX, {"app": "milvus"}),
            Pod("qdrant-0",       NS_ORDINOX, {"app": "qdrant"}),
            Pod("coredns-1",      NS_KUBE_SYSTEM, {"k8s-app": "kube-dns"}),
        ],
    )


class TestPolicyEvaluation:
    def test_pod_with_no_matching_policy_is_default_allow(self):
        c = _basic_cluster()
        # No policies at all -> all egress permitted (k8s default).
        echo = c.pods[0]
        redis = c.pods[4]
        assert c.can_egress(echo, dst_pod=redis, port=6379) is Decision.ALLOWED

    def test_default_deny_egress_blocks_everything(self):
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "deny-all-egress", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {},        # selects every pod in the namespace
                "policyTypes": ["Egress"],
                # no egress rules -> default-deny for selected pods
            },
        }]
        echo, redis = c.pods[0], c.pods[4]
        assert c.can_egress(echo, dst_pod=redis, port=6379) is Decision.DENIED

    def test_allow_redis_egress_permits_only_redis(self):
        c = _basic_cluster()
        c.policies = [
            {
                "metadata": {"name": "deny-all-egress", "namespace": NS_ORDINOX},
                "spec": {"podSelector": {}, "policyTypes": ["Egress"]},
            },
            {
                "metadata": {"name": "echo-allow-redis", "namespace": NS_ORDINOX},
                "spec": {
                    "podSelector": {"matchLabels": {"app": "echo-agent"}},
                    "policyTypes": ["Egress"],
                    "egress": [{
                        "to": [{"podSelector": {"matchLabels": {"app": "redis"}}}],
                        "ports": [{"port": 6379, "protocol": "TCP"}],
                    }],
                },
            },
        ]
        echo, redis, postgres = c.pods[0], c.pods[4], c.pods[5]
        assert c.can_egress(echo, dst_pod=redis, port=6379) is Decision.ALLOWED
        assert c.can_egress(echo, dst_pod=postgres, port=5432) is Decision.DENIED

    def test_multi_policy_union_allows_either(self):
        """Two allow-policies for the same pod -> union; either lets traffic through."""
        c = _basic_cluster()
        c.policies = [
            {
                "metadata": {"name": "deny-all", "namespace": NS_ORDINOX},
                "spec": {"podSelector": {}, "policyTypes": ["Egress"]},
            },
            {
                "metadata": {"name": "allow-redis", "namespace": NS_ORDINOX},
                "spec": {
                    "podSelector": {"matchLabels": {"app": "echo-agent"}},
                    "policyTypes": ["Egress"],
                    "egress": [{"to": [{"podSelector": {"matchLabels": {"app": "redis"}}}],
                                "ports": [{"port": 6379, "protocol": "TCP"}]}],
                },
            },
            {
                "metadata": {"name": "allow-postgres", "namespace": NS_ORDINOX},
                "spec": {
                    "podSelector": {"matchLabels": {"app": "echo-agent"}},
                    "policyTypes": ["Egress"],
                    "egress": [{"to": [{"podSelector": {"matchLabels": {"app": "postgres"}}}],
                                "ports": [{"port": 5432, "protocol": "TCP"}]}],
                },
            },
        ]
        echo = c.pods[0]
        assert c.can_egress(echo, dst_pod=c.pods[4], port=6379) is Decision.ALLOWED
        assert c.can_egress(echo, dst_pod=c.pods[5], port=5432) is Decision.ALLOWED

    def test_only_ingress_policy_does_not_affect_egress(self):
        """A policy with only `policyTypes: [Ingress]` leaves egress default-allow."""
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "echo-deny-ingress", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "echo-agent"}},
                "policyTypes": ["Ingress"],
            },
        }]
        echo = c.pods[0]
        # Egress unchanged from default-allow:
        assert c.can_egress(echo, dst_pod=c.pods[4], port=6379) is Decision.ALLOWED

    def test_port_mismatch_denies(self):
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "allow-redis-port", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "echo-agent"}},
                "policyTypes": ["Egress"],
                "egress": [{
                    "to": [{"podSelector": {"matchLabels": {"app": "redis"}}}],
                    "ports": [{"port": 6379, "protocol": "TCP"}],
                }],
            },
        }]
        echo, redis = c.pods[0], c.pods[4]
        assert c.can_egress(echo, dst_pod=redis, port=6379) is Decision.ALLOWED
        # Right pod, wrong port — denied.
        assert c.can_egress(echo, dst_pod=redis, port=80) is Decision.DENIED

    def test_dns_to_kube_system_with_canonical_label_allows_REGRESSION(self):
        """The Day 8 regression in the simulator. With the canonical label,
        DNS egress is allowed; with the legacy `name` label, it isn't."""
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "echo-allow-dns", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "echo-agent"}},
                "policyTypes": ["Egress"],
                "egress": [{
                    "to": [{"namespaceSelector": {
                        "matchLabels": {"kubernetes.io/metadata.name": "kube-system"},
                    }}],
                    "ports": [{"port": 53, "protocol": "UDP"},
                              {"port": 53, "protocol": "TCP"}],
                }],
            },
        }]
        echo, coredns = c.pods[0], c.pods[9]
        assert c.can_egress(echo, dst_pod=coredns, port=53, protocol="UDP") is Decision.ALLOWED
        assert c.can_egress(echo, dst_pod=coredns, port=53, protocol="TCP") is Decision.ALLOWED

    def test_dns_to_kube_system_with_legacy_label_denies_REGRESSION(self):
        """Same setup but with the broken legacy selector. Demonstrates the bug."""
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "echo-broken-dns", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "echo-agent"}},
                "policyTypes": ["Egress"],
                "egress": [{
                    "to": [{"namespaceSelector": {"matchLabels": {"name": "kube-system"}}}],
                    "ports": [{"port": 53, "protocol": "UDP"}],
                }],
            },
        }]
        echo, coredns = c.pods[0], c.pods[9]
        # kube-system doesn't carry the legacy `name` label by default
        # -> namespaceSelector misses -> rule doesn't allow -> default-deny fires.
        assert c.can_egress(echo, dst_pod=coredns, port=53, protocol="UDP") is Decision.DENIED

    def test_ipblock_egress_to_external_ip(self):
        """Anthropic-style external egress: allow 0.0.0.0/0 except RFC1918."""
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "orch-external", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "orchestrator-agent"}},
                "policyTypes": ["Egress"],
                "egress": [{
                    "to": [{"ipBlock": {
                        "cidr": "0.0.0.0/0",
                        "except": ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"],
                    }}],
                    "ports": [{"port": 443, "protocol": "TCP"}],
                }],
            },
        }]
        orch = c.pods[1]
        # Public IP — allowed.
        assert c.can_egress(orch, dst_ip="1.1.1.1", port=443) is Decision.ALLOWED
        # RFC1918 — denied by `except`.
        assert c.can_egress(orch, dst_ip="10.0.0.5", port=443) is Decision.DENIED
        # Right peer, wrong port.
        assert c.can_egress(orch, dst_ip="1.1.1.1", port=80) is Decision.DENIED

    def test_empty_to_in_rule_means_any_peer(self):
        """A rule with no `to:` peers but a port = wide-open egress on that port."""
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "echo-allow-any", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "echo-agent"}},
                "policyTypes": ["Egress"],
                "egress": [{"ports": [{"port": 443, "protocol": "TCP"}]}],
            },
        }]
        echo = c.pods[0]
        assert c.can_egress(echo, dst_ip="anything", port=443) is Decision.ALLOWED
        assert c.can_egress(echo, dst_pod=c.pods[5], port=443) is Decision.ALLOWED

    def test_can_ingress_basic(self):
        """Ingress evaluation mirrors egress. Verify the entry point works."""
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "redis-allow-ingress-from-echo", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "redis"}},
                "policyTypes": ["Ingress"],
                "ingress": [{
                    "from": [{"podSelector": {"matchLabels": {"app": "echo-agent"}}}],
                    "ports": [{"port": 6379, "protocol": "TCP"}],
                }],
            },
        }]
        echo, redis, postgres = c.pods[0], c.pods[4], c.pods[5]
        # Echo → Redis: allowed (rule says from echo).
        assert c.can_ingress(redis, src_pod=echo, port=6379) is Decision.ALLOWED
        # Postgres → Redis: denied (postgres not in `from`).
        assert c.can_ingress(redis, src_pod=postgres, port=6379) is Decision.DENIED

    def test_namespace_lookup_missing_returns_none(self):
        c = _basic_cluster()
        assert c.namespace("does-not-exist") is None

    def test_peer_with_namespace_selector_for_missing_namespace_denies(self):
        """Defensive: a namespaceSelector pointing at a namespace the
        simulator doesn't know about should deny, not crash."""
        c = _basic_cluster()
        # Remove kube-system so the namespace lookup misses.
        c.namespaces = [n for n in c.namespaces if n.name != NS_KUBE_SYSTEM]
        c.policies = [{
            "metadata": {"name": "echo-allow-kube-system", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "echo-agent"}},
                "policyTypes": ["Egress"],
                "egress": [{
                    "to": [{"namespaceSelector": {
                        "matchLabels": {"kubernetes.io/metadata.name": "kube-system"}}}],
                    "ports": [{"port": 53, "protocol": "UDP"}],
                }],
            },
        }]
        echo, coredns = c.pods[0], c.pods[9]
        assert c.can_egress(echo, dst_pod=coredns, port=53, protocol="UDP") is Decision.DENIED


class TestSelectorEdgeCases:
    """Selector operators not covered by the main TestSelectors block."""

    def test_match_expressions_does_not_exist_operator(self):
        sel = {"matchExpressions": [{"key": "deprecated", "operator": "DoesNotExist"}]}
        assert _matches_selector({"app": "redis"}, sel)
        assert not _matches_selector({"app": "redis", "deprecated": "true"}, sel)

    def test_match_expressions_unsupported_operator_raises(self):
        sel = {"matchExpressions": [{"key": "x", "operator": "MaybeMatches"}]}
        with pytest.raises(ValueError, match="unsupported"):
            _matches_selector({"x": "y"}, sel)

    def test_port_named_port_in_policy_ignored(self):
        """Named ports (`port: "http"`) aren't modeled; rule is skipped."""
        assert not _port_matches([{"port": "http", "protocol": "TCP"}], 80, "TCP")

    def test_port_missing_port_key_skipped(self):
        """A ports entry with no `port` field shouldn't crash."""
        assert not _port_matches([{"protocol": "TCP"}], 80, "TCP")

    def test_peer_with_ipblock_but_no_dst_ip_denies(self):
        """ipBlock rule against a pod (not an IP) doesn't match."""
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "echo-external-only", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "echo-agent"}},
                "policyTypes": ["Egress"],
                "egress": [{"to": [{"ipBlock": {"cidr": "0.0.0.0/0"}}],
                            "ports": [{"port": 443, "protocol": "TCP"}]}],
            },
        }]
        echo, redis = c.pods[0], c.pods[4]
        # Asking about pod-to-pod traffic with only an ipBlock rule -> denied.
        assert c.can_egress(echo, dst_pod=redis, port=443) is Decision.DENIED

    def test_peer_with_pod_selector_but_no_dst_pod_denies(self):
        c = _basic_cluster()
        c.policies = [{
            "metadata": {"name": "echo-pod-only", "namespace": NS_ORDINOX},
            "spec": {
                "podSelector": {"matchLabels": {"app": "echo-agent"}},
                "policyTypes": ["Egress"],
                "egress": [{
                    "to": [{"podSelector": {"matchLabels": {"app": "redis"}}}],
                    "ports": [{"port": 6379, "protocol": "TCP"}],
                }],
            },
        }]
        echo = c.pods[0]
        # Asking about pod-to-ip traffic with only a podSelector rule -> denied.
        assert c.can_egress(echo, dst_ip="1.1.1.1", port=6379) is Decision.DENIED

    def test_pod_and_namespace_are_hashable(self):
        """Required for using them in sets/dicts (some test patterns rely on this)."""
        p1 = Pod("a", "ns", {"x": "y"})
        p2 = Pod("a", "ns", {"x": "z"})  # same name+ns, different labels
        # Hash on identity (name, namespace) only -> these collide intentionally.
        assert hash(p1) == hash(p2)
        n1 = Namespace.canonical("kube-system")
        assert hash(n1) == hash(Namespace.canonical("kube-system"))


# ============================================================
# 4. Real generated policies — end-to-end
# ============================================================

@pytest.fixture(scope="module")
def real_policies() -> list[dict[str, Any]]:
    path = Path(__file__).resolve().parents[2] / "infrastructure" / "k3s" \
           / "network-policies-per-agent.yaml"
    if not path.is_file():
        pytest.skip(f"{path} missing — run scripts/security/generate_policies.py")
    docs = [d for d in yaml.safe_load_all(path.read_text(encoding="utf-8")) if d is not None]
    np_docs = [d for d in docs if d.get("kind") == "NetworkPolicy"]
    assert np_docs, "no NetworkPolicy docs in generated file"
    return np_docs


@pytest.fixture
def real_cluster(real_policies) -> Cluster:
    c = _basic_cluster()
    # Add baseline default-deny + allow-internal — our namespace.yaml has these.
    # Without them, the per-agent egress rules would be additive on top of an
    # already-permissive default. We model the realistic combined state.
    c.policies = [
        {
            "metadata": {"name": "default-deny-all", "namespace": NS_ORDINOX},
            "spec": {"podSelector": {}, "policyTypes": ["Ingress", "Egress"]},
        },
    ] + real_policies
    return c


class TestGeneratedPolicies:
    """Each agent should reach exactly what `capabilities.yaml` declares.

    Asserted positively (must reach) AND negatively (must NOT reach) so a
    future capabilities edit that accidentally widens or narrows scope
    fails this suite immediately.
    """

    def test_echo_agent_can_reach_redis_postgres_jaeger(self, real_cluster):
        echo = real_cluster.pods[0]
        assert real_cluster.can_egress(echo, dst_pod=real_cluster.pods[4], port=6379) is Decision.ALLOWED
        assert real_cluster.can_egress(echo, dst_pod=real_cluster.pods[5], port=5432) is Decision.ALLOWED
        assert real_cluster.can_egress(echo, dst_pod=real_cluster.pods[6], port=4317) is Decision.ALLOWED

    def test_echo_agent_cannot_reach_anthropic(self, real_cluster):
        """Echo doesn't talk to LLMs — must be denied external egress."""
        echo = real_cluster.pods[0]
        assert real_cluster.can_egress(echo, dst_ip="1.1.1.1", port=443) is Decision.DENIED

    def test_echo_agent_cannot_reach_milvus(self, real_cluster):
        """Echo isn't in compliance/analyst — must not reach vector DBs."""
        echo = real_cluster.pods[0]
        assert real_cluster.can_egress(echo, dst_pod=real_cluster.pods[7], port=19530) is Decision.DENIED

    def test_orchestrator_can_reach_anthropic(self, real_cluster):
        orch = real_cluster.pods[1]
        assert real_cluster.can_egress(orch, dst_ip="1.1.1.1", port=443) is Decision.ALLOWED

    def test_orchestrator_external_blocked_for_rfc1918(self, real_cluster):
        """ipBlock `except` must keep cluster-internal egress controlled by other rules."""
        orch = real_cluster.pods[1]
        # 10.x via ipBlock peer would be denied. But this is the external rule;
        # in-cluster traffic to postgres is handled by the OTHER egress rule
        # (podSelector). Both must work; this test checks the external peer
        # is correctly bounded by `except`.
        assert real_cluster.can_egress(orch, dst_ip="10.0.0.5", port=443) is Decision.DENIED

    def test_compliance_agent_can_reach_qdrant(self, real_cluster):
        comp = real_cluster.pods[2]
        assert real_cluster.can_egress(comp, dst_pod=real_cluster.pods[8], port=6333) is Decision.ALLOWED

    def test_compliance_agent_cannot_reach_anthropic(self, real_cluster):
        """Compliance isn't in external_allow — no Anthropic egress."""
        comp = real_cluster.pods[2]
        assert real_cluster.can_egress(comp, dst_ip="1.1.1.1", port=443) is Decision.DENIED

    def test_analyst_can_reach_milvus_and_anthropic(self, real_cluster):
        analyst = real_cluster.pods[3]
        assert real_cluster.can_egress(analyst, dst_pod=real_cluster.pods[7], port=19530) is Decision.ALLOWED
        assert real_cluster.can_egress(analyst, dst_ip="1.1.1.1", port=443) is Decision.ALLOWED

    def test_every_agent_can_dns_to_kube_system_REGRESSION(self, real_cluster):
        """The Day 8 fix end-to-end against the *actual generated YAML*.

        If the regression in generate_policies.py ever comes back, this test
        fails for all four agents simultaneously — a loud signal."""
        coredns = real_cluster.pods[9]
        for agent in real_cluster.pods[:4]:
            udp = real_cluster.can_egress(agent, dst_pod=coredns, port=53, protocol="UDP")
            tcp = real_cluster.can_egress(agent, dst_pod=coredns, port=53, protocol="TCP")
            assert udp is Decision.ALLOWED, f"{agent.name} cannot DNS to kube-system over UDP"
            assert tcp is Decision.ALLOWED, f"{agent.name} cannot DNS to kube-system over TCP"

    def test_every_agent_can_reach_redis_for_streams(self, real_cluster):
        """All four agents need Redis Streams — it's the bus."""
        for agent in real_cluster.pods[:4]:
            assert real_cluster.can_egress(
                agent, dst_pod=real_cluster.pods[4], port=6379
            ) is Decision.ALLOWED, f"{agent.name} cannot reach redis"

    def test_no_agent_can_egress_random_external(self, real_cluster):
        """Random non-Anthropic external (e.g., 8.8.8.8:53) — should be denied
        for agents without external_allow. For analyst/orchestrator it would
        be allowed because external_allow is coarse (0.0.0.0/0 except RFC1918).
        This documents that coarse-ness — Sprint 8 hardening tightens it."""
        for agent in (real_cluster.pods[0], real_cluster.pods[2]):  # echo, compliance
            assert real_cluster.can_egress(agent, dst_ip="8.8.8.8", port=443) is Decision.DENIED

    def test_orchestrator_external_is_coarse_known_limitation(self, real_cluster):
        """Orchestrator's ipBlock matches 0.0.0.0/0 — so 8.8.8.8 reaches too.
        Asserted explicitly to document the known limitation; Sprint 8 should
        replace with an egress gateway for fine-grained per-hostname allow."""
        orch = real_cluster.pods[1]
        assert real_cluster.can_egress(orch, dst_ip="8.8.8.8", port=443) is Decision.ALLOWED
