apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ordinox-ai
resources:
  - compliance-service-deployment.yaml
  - compliance-service-svc.yaml
  - blue-green-traffic-split.yaml
