apiVersion: v1
kind: Namespace
metadata:
  name: ordinoxai-prod
  labels:
    app.kubernetes.io/name: ordinoxai
    app.kubernetes.io/domain: ordinoxai.com
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
