apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: ordinoxai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: compliance-service
            port:
              number: 8000
